use_frameworks!

target 'myLibrary_Example' do
  pod 'myLibrary', :path => '../'

  target 'myLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
